### ISSUE TITLE
create template script for batch export

### ISSUE THREAD

**Issue by HoldenJe** [LakeErie-PreyFish-Acoustics/erieacoustics#19]
Similar to `1_import_data_to_template.R` create a new template with starter code to batch export all processed transects/grids.

**Comment by mrdufour** [comment]
I think this is complete? The  `erieacoustics::finish_setup()` functions now generates both '1_import_data_to_template.R' and '2_export_data_from_EV.R' scripts.

**Comment by HoldenJe** [comment]
Changes merged here: 20f199da08f8aee3617fab24b92109225fcdbff3
Closed.
