### ISSUE TITLE
add annual protocol .rmd

### ISSUE THREAD

**Issue by mrdufour** [LakeErie-PreyFish-Acoustics/erieacoustics#31]
Automatically import skeleton .rmd file into 1_Annual_Protocol folder.

**Comment by HoldenJe** [comment]
@mrdufour - review template file (https://github.com/LakeErie-PreyFish-Acoustics/erieacoustics/blob/31-add-annual-protocol-rmd/inst/templates/annual_survey_template.Rmd). If adequate this can be merged to Development.

**Comment by mrdufour** [comment]
Thinking about how we use the data downstream, it would be great to include the strata number. Jeremy, you've got it plugged in the protocol as "S1_". For the single digit strata, we may want to use "S01_" so that when we get to the "S10_" and greater they don't slide in between "S1_" and "S2_". This came up as an issue when doing some plotting a while back. What do you think?

Also, I've been adding the grid number as the second half of the transect name. For example, "S03_324" represents the transect collected from 5-min grid 324 in strata 3.  You are using "_R21" for what I think is the 21st randomly selected transect. What do you think about the two approaches?
