### ISSUE TITLE
add data aggregation/density calculation script

### ISSUE THREAD

**Issue by mrdufour** [LakeErie-PreyFish-Acoustics/erieacoustics#32]
Finalize script that generates hacdat.csv, histo.csv, and histohac.csv, and automatically add to 7_Annual_Summary folder.

**Comment by mrdufour** [comment]
Jeremy will outline how to add script to the package and auto-populate through the 'finish_setup" function.
Mark will update/finalize script, taking into account the formalized naming convention "Basin_strata_grid#"

**Comment by HoldenJe** [comment]
@mrdufour - here's the steps:
1. From the issue create a new branch
2. Switch to the branch on your local machine
3. Create/copy/save the script as a regular *.R file in the "inst/templates" directory (see "export_from_EV.R")
4. Commit this change
5. Open "R/finish_setup().R"
6. Add a code snippet similar to:
```
usethis::use_template(
      template = "export_from_EV.R",
      save_as = "7_Annual_Summary/2_export_data_from_EV.R",
      package = "erieacoustics"
    )
```
7. Commit this change
8. Rename the "finish_setup().R" as "finish_setup.R" (*this just cleans up a sloppy file naming mistake*)
9. Commit this change
10. Probably best to do a "build and reload" at this point to check that all features are working as intended.
11. Push to the repo
12. Initiate a pull request to development branch
