### ISSUE TITLE
modify export function to check for different gps names

### ISSUE THREAD

**Issue by HoldenJe** [LakeErie-PreyFish-Acoustics/erieacoustics#7]
development branch has merged code changes from @mrdufour that require changes to:
1. check for a variable name that doesn't exist
2. attempt to export using default name
3. if export attempt returns false, try different name
4. if both false, provide error message but continue with remainder of export since gps export should be a warning, not a fatal error.

**Comment by mrdufour** [comment]
Close - Maintain basin specific templates
